services:
  sumup:
    build: .
    ports:
      - "4000:4000"
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s